[package]
name = "keylogger"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
winapi = { version = "0.3.9", features = ["winuser", "libloaderapi", "minwindef", "ntdef", "processthreadsapi", "winbase"] }
chrono = "0.4"
rdev = "0.5.3"
widestring =  "1.1.0"